export interface UserData{
    
    id: number,
    fullname: string,
    email: string,
    mobile_number: string,
    code: string,
    usertag: string,
    email_verified_at: string,
    profile_image: string,
    referral_code: string,
    reffered_by: string,
    security_pin: string,
    country: string,
    status: number,
    commission: number,
    balance: number,
    app_status: number,
    email_status: number,
    currency: string,
    deleted_at: string,
    created_at: string,
    updated_at: string,
    wallet_count: number,
    roletype: boolean,
    permissions: [],
    roles: []
}